name: Bug Report
description: Report a bug in an existing integration or core functionality
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: dropdown
    id: integration-type
    attributes:
      label: Integration Type
      description: What type of integration is affected?
      options:
        - Charger
        - Meter
        - Core/Other
    validations:
      required: true

  - type: input
    id: integration-name
    attributes:
      label: Integration Name
      description: Which specific integration is affected? (e.g., "Easee", "Zaptec", "HomeWizard")
      placeholder: "ex. Easee"
    validations:
      required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the problem you're experiencing
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happens
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Configure '...'
        3. See error
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output from Home Assistant
      render: shell
      placeholder: Paste logs here
    validations:
      required: false

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: "ex. 2024.1.0"
    validations:
      required: false

  - type: input
    id: integration-version
    attributes:
      label: EVSE Load Balancer Version
      description: What version of this integration are you running?
      placeholder: "ex. 1.2.3"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, configuration details, etc.
    validations:
      required: false
